name: Build and push docker image
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: aschmelyun/cleaver:latest
    steps:
      - run: docker login gitea.dineease.com -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASSWORD}}
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build . -t gitea.dineease.com/${{gitea.actor}}/module-a:latest
      - run: docker push gitea.dineease.com/${{gitea.actor}}/module-a:latest
