
name: Build and push docker image
on: [push]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login gitea.dineease.com -u ${{secrets.REGISTRY_USER}} --password-stdin
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build . -t gitea.dineease.com/${{gitea.actor}}/module-a:latest
      - run: docker push gitea.dineease.com/${{gitea.actor}}/module-a:latest
